function [fitresult, gof] = createFit1(x, DF_mean)
%CREATEFIT1(X,DF_MEAN)
%  Create a fit.
%
%  Data for 'fit curve DF' fit:
%      X Input : x
%      Y Output: DF_mean
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-May-2020 18:19:15


%% Fit: 'fit curve DF'.
[xData, yData] = prepareCurveData( x, DF_mean );

% Set up fittype and options.
ft = fittype( 'poly4' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'fit curve DF' );
h = plot( fitresult, xData, yData );
legend( h, 'DF_mean', 'fit curve DF', 'Location', 'NorthEast' );
% Label axes
xlabel 'Time in oven (m)'
ylabel 'Delta Frequency (Hz)'
grid on


