function [fitresult, gof] = createFit(x, mean_values)
%CREATEFIT(X,MEAN_VALUES)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: mean_values
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-May-2020 13:46:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, mean_values );

% Set up fittype and options.
ft = fittype( 'poly4' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'mean\_values vs. x', 'poly fit d=4', 'Location', 'East' );
% Label axes
xlabel 'Time in Oven (m)'
ylabel 'Frequency (GHz)'
grid on


